// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: feedcatter/service.proto

package feedcatter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateFoodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFoodRequest) Reset() {
	*x = CreateFoodRequest{}
	mi := &file_feedcatter_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFoodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFoodRequest) ProtoMessage() {}

func (x *CreateFoodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feedcatter_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFoodRequest.ProtoReflect.Descriptor instead.
func (*CreateFoodRequest) Descriptor() ([]byte, []int) {
	return file_feedcatter_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateFoodRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateFoodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Food          *Food                  `protobuf:"bytes,1,opt,name=food,proto3" json:"food,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFoodResponse) Reset() {
	*x = CreateFoodResponse{}
	mi := &file_feedcatter_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFoodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFoodResponse) ProtoMessage() {}

func (x *CreateFoodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feedcatter_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFoodResponse.ProtoReflect.Descriptor instead.
func (*CreateFoodResponse) Descriptor() ([]byte, []int) {
	return file_feedcatter_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFoodResponse) GetFood() *Food {
	if x != nil {
		return x.Food
	}
	return nil
}

type DeleteFoodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Food          int32                  `protobuf:"varint,1,opt,name=food,proto3" json:"food,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFoodRequest) Reset() {
	*x = DeleteFoodRequest{}
	mi := &file_feedcatter_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFoodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFoodRequest) ProtoMessage() {}

func (x *DeleteFoodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feedcatter_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFoodRequest.ProtoReflect.Descriptor instead.
func (*DeleteFoodRequest) Descriptor() ([]byte, []int) {
	return file_feedcatter_service_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteFoodRequest) GetFood() int32 {
	if x != nil {
		return x.Food
	}
	return 0
}

type DeleteFoodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFoodResponse) Reset() {
	*x = DeleteFoodResponse{}
	mi := &file_feedcatter_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFoodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFoodResponse) ProtoMessage() {}

func (x *DeleteFoodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feedcatter_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFoodResponse.ProtoReflect.Descriptor instead.
func (*DeleteFoodResponse) Descriptor() ([]byte, []int) {
	return file_feedcatter_service_proto_rawDescGZIP(), []int{3}
}

type ListFoodsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFoodsRequest) Reset() {
	*x = ListFoodsRequest{}
	mi := &file_feedcatter_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFoodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFoodsRequest) ProtoMessage() {}

func (x *ListFoodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feedcatter_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFoodsRequest.ProtoReflect.Descriptor instead.
func (*ListFoodsRequest) Descriptor() ([]byte, []int) {
	return file_feedcatter_service_proto_rawDescGZIP(), []int{4}
}

type ListFoodsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Foods         []*Food                `protobuf:"bytes,1,rep,name=foods,proto3" json:"foods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFoodsResponse) Reset() {
	*x = ListFoodsResponse{}
	mi := &file_feedcatter_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFoodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFoodsResponse) ProtoMessage() {}

func (x *ListFoodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feedcatter_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFoodsResponse.ProtoReflect.Descriptor instead.
func (*ListFoodsResponse) Descriptor() ([]byte, []int) {
	return file_feedcatter_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListFoodsResponse) GetFoods() []*Food {
	if x != nil {
		return x.Foods
	}
	return nil
}

type SuggestFoodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestFoodRequest) Reset() {
	*x = SuggestFoodRequest{}
	mi := &file_feedcatter_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestFoodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestFoodRequest) ProtoMessage() {}

func (x *SuggestFoodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feedcatter_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestFoodRequest.ProtoReflect.Descriptor instead.
func (*SuggestFoodRequest) Descriptor() ([]byte, []int) {
	return file_feedcatter_service_proto_rawDescGZIP(), []int{6}
}

type SuggestFoodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Food          *Food                  `protobuf:"bytes,1,opt,name=food,proto3" json:"food,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestFoodResponse) Reset() {
	*x = SuggestFoodResponse{}
	mi := &file_feedcatter_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestFoodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestFoodResponse) ProtoMessage() {}

func (x *SuggestFoodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feedcatter_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestFoodResponse.ProtoReflect.Descriptor instead.
func (*SuggestFoodResponse) Descriptor() ([]byte, []int) {
	return file_feedcatter_service_proto_rawDescGZIP(), []int{7}
}

func (x *SuggestFoodResponse) GetFood() *Food {
	if x != nil {
		return x.Food
	}
	return nil
}

type FeedFoodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Food          int32                  `protobuf:"varint,1,opt,name=food,proto3" json:"food,omitempty"`
	Percentage    float64                `protobuf:"fixed64,2,opt,name=percentage,proto3" json:"percentage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedFoodRequest) Reset() {
	*x = FeedFoodRequest{}
	mi := &file_feedcatter_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedFoodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedFoodRequest) ProtoMessage() {}

func (x *FeedFoodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feedcatter_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedFoodRequest.ProtoReflect.Descriptor instead.
func (*FeedFoodRequest) Descriptor() ([]byte, []int) {
	return file_feedcatter_service_proto_rawDescGZIP(), []int{8}
}

func (x *FeedFoodRequest) GetFood() int32 {
	if x != nil {
		return x.Food
	}
	return 0
}

func (x *FeedFoodRequest) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

type FeedFoodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Food          *Food                  `protobuf:"bytes,1,opt,name=food,proto3" json:"food,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedFoodResponse) Reset() {
	*x = FeedFoodResponse{}
	mi := &file_feedcatter_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedFoodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedFoodResponse) ProtoMessage() {}

func (x *FeedFoodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feedcatter_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedFoodResponse.ProtoReflect.Descriptor instead.
func (*FeedFoodResponse) Descriptor() ([]byte, []int) {
	return file_feedcatter_service_proto_rawDescGZIP(), []int{9}
}

func (x *FeedFoodResponse) GetFood() *Food {
	if x != nil {
		return x.Food
	}
	return nil
}

var File_feedcatter_service_proto protoreflect.FileDescriptor

const file_feedcatter_service_proto_rawDesc = "" +
	"\n" +
	"\x18feedcatter/service.proto\x12\n" +
	"feedcatter\x1a\x15feedcatter/food.proto\"'\n" +
	"\x11CreateFoodRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\":\n" +
	"\x12CreateFoodResponse\x12$\n" +
	"\x04food\x18\x01 \x01(\v2\x10.feedcatter.FoodR\x04food\"'\n" +
	"\x11DeleteFoodRequest\x12\x12\n" +
	"\x04food\x18\x01 \x01(\x05R\x04food\"\x14\n" +
	"\x12DeleteFoodResponse\"\x12\n" +
	"\x10ListFoodsRequest\";\n" +
	"\x11ListFoodsResponse\x12&\n" +
	"\x05foods\x18\x01 \x03(\v2\x10.feedcatter.FoodR\x05foods\"\x14\n" +
	"\x12SuggestFoodRequest\";\n" +
	"\x13SuggestFoodResponse\x12$\n" +
	"\x04food\x18\x01 \x01(\v2\x10.feedcatter.FoodR\x04food\"E\n" +
	"\x0fFeedFoodRequest\x12\x12\n" +
	"\x04food\x18\x01 \x01(\x05R\x04food\x12\x1e\n" +
	"\n" +
	"percentage\x18\x02 \x01(\x01R\n" +
	"percentage\"8\n" +
	"\x10FeedFoodResponse\x12$\n" +
	"\x04food\x18\x01 \x01(\v2\x10.feedcatter.FoodR\x04food2\x98\x03\n" +
	"\x11FeedcatterService\x12M\n" +
	"\n" +
	"CreateFood\x12\x1d.feedcatter.CreateFoodRequest\x1a\x1e.feedcatter.CreateFoodResponse\"\x00\x12M\n" +
	"\n" +
	"DeleteFood\x12\x1d.feedcatter.DeleteFoodRequest\x1a\x1e.feedcatter.DeleteFoodResponse\"\x00\x12J\n" +
	"\tListFoods\x12\x1c.feedcatter.ListFoodsRequest\x1a\x1d.feedcatter.ListFoodsResponse\"\x00\x12P\n" +
	"\vSuggestFood\x12\x1e.feedcatter.SuggestFoodRequest\x1a\x1f.feedcatter.SuggestFoodResponse\"\x00\x12G\n" +
	"\bFeedFood\x12\x1b.feedcatter.FeedFoodRequest\x1a\x1c.feedcatter.FeedFoodResponse\"\x00BCZAgithub.com/Artamus/feedcatter/feedcatter-go/feedcatter;feedcatterb\x06proto3"

var (
	file_feedcatter_service_proto_rawDescOnce sync.Once
	file_feedcatter_service_proto_rawDescData []byte
)

func file_feedcatter_service_proto_rawDescGZIP() []byte {
	file_feedcatter_service_proto_rawDescOnce.Do(func() {
		file_feedcatter_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_feedcatter_service_proto_rawDesc), len(file_feedcatter_service_proto_rawDesc)))
	})
	return file_feedcatter_service_proto_rawDescData
}

var file_feedcatter_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_feedcatter_service_proto_goTypes = []any{
	(*CreateFoodRequest)(nil),   // 0: feedcatter.CreateFoodRequest
	(*CreateFoodResponse)(nil),  // 1: feedcatter.CreateFoodResponse
	(*DeleteFoodRequest)(nil),   // 2: feedcatter.DeleteFoodRequest
	(*DeleteFoodResponse)(nil),  // 3: feedcatter.DeleteFoodResponse
	(*ListFoodsRequest)(nil),    // 4: feedcatter.ListFoodsRequest
	(*ListFoodsResponse)(nil),   // 5: feedcatter.ListFoodsResponse
	(*SuggestFoodRequest)(nil),  // 6: feedcatter.SuggestFoodRequest
	(*SuggestFoodResponse)(nil), // 7: feedcatter.SuggestFoodResponse
	(*FeedFoodRequest)(nil),     // 8: feedcatter.FeedFoodRequest
	(*FeedFoodResponse)(nil),    // 9: feedcatter.FeedFoodResponse
	(*Food)(nil),                // 10: feedcatter.Food
}
var file_feedcatter_service_proto_depIdxs = []int32{
	10, // 0: feedcatter.CreateFoodResponse.food:type_name -> feedcatter.Food
	10, // 1: feedcatter.ListFoodsResponse.foods:type_name -> feedcatter.Food
	10, // 2: feedcatter.SuggestFoodResponse.food:type_name -> feedcatter.Food
	10, // 3: feedcatter.FeedFoodResponse.food:type_name -> feedcatter.Food
	0,  // 4: feedcatter.FeedcatterService.CreateFood:input_type -> feedcatter.CreateFoodRequest
	2,  // 5: feedcatter.FeedcatterService.DeleteFood:input_type -> feedcatter.DeleteFoodRequest
	4,  // 6: feedcatter.FeedcatterService.ListFoods:input_type -> feedcatter.ListFoodsRequest
	6,  // 7: feedcatter.FeedcatterService.SuggestFood:input_type -> feedcatter.SuggestFoodRequest
	8,  // 8: feedcatter.FeedcatterService.FeedFood:input_type -> feedcatter.FeedFoodRequest
	1,  // 9: feedcatter.FeedcatterService.CreateFood:output_type -> feedcatter.CreateFoodResponse
	3,  // 10: feedcatter.FeedcatterService.DeleteFood:output_type -> feedcatter.DeleteFoodResponse
	5,  // 11: feedcatter.FeedcatterService.ListFoods:output_type -> feedcatter.ListFoodsResponse
	7,  // 12: feedcatter.FeedcatterService.SuggestFood:output_type -> feedcatter.SuggestFoodResponse
	9,  // 13: feedcatter.FeedcatterService.FeedFood:output_type -> feedcatter.FeedFoodResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_feedcatter_service_proto_init() }
func file_feedcatter_service_proto_init() {
	if File_feedcatter_service_proto != nil {
		return
	}
	file_feedcatter_food_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_feedcatter_service_proto_rawDesc), len(file_feedcatter_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_feedcatter_service_proto_goTypes,
		DependencyIndexes: file_feedcatter_service_proto_depIdxs,
		MessageInfos:      file_feedcatter_service_proto_msgTypes,
	}.Build()
	File_feedcatter_service_proto = out.File
	file_feedcatter_service_proto_goTypes = nil
	file_feedcatter_service_proto_depIdxs = nil
}
